/**
  ******************************************************************************
  * @file      	SansSerif12.cpp
  * @author    	Tecnologic86
  * @version   	V0.0.0
  * @date      	17.02.12
  * @brief		big font for Graphics Display
  *
  *
  * Generated by GLCD Font Generator from Mikrocontroller.net
  ******************************************************************************
  */

/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef SANSSERIF12_H_
#define SANSSERIF12_H_
/* Includes ------------------------------------------------------------------*/
#include "CGraphicLCD.h"
/* Exported types ------------------------------------------------------------*/
/* Exported constants --------------------------------------------------------*/
extern const tFont c_FontSansSerif26;
/* Exported macro ------------------------------------------------------------*/
/* Exported functions ------------------------------------------------------- */
/* Class definitions -------------------------------------------------------- */

#endif /* SANSSERIF12_H_ */
